#!/bin/sh

operating_dir=`dirname $0`

conf_file=$operating_dir/sc.conf
if [ $# -eq 1 ]; then
  conf_file=$1
fi

if [ ! -f $conf_file ]; then
  echo There is no such configuration file : $conf_file
  exit 1
fi

. $conf_file

mkdir -p $operating_dir/pid

base_jvm_opts="-Dcassandra.log.dir=$operating_dir/log"
if [ $property_file ]; then
  base_jvm_opts="$base_jvm_opts"
fi
export CASSANDRA_HOME=$cassandra_home
i=`expr $num_node / 2 + 1`
while [ $i -le $num_node ]; do
  if [ $id_offset ]; then
    id=`expr \( $id_offset - 1 \) \* $num_node + $i`
  else
    id=$i
  fi
  export CASSANDRA_CONF=$operating_dir/cassconf/conf$i
  export JVM_OPTS="$base_jvm_opts -Dlog4j.file.id=$i -Dcassandra.id=$id -Dcassandra.ring_delay_ms=15000"
  export NODE_ID=$i
  bin/cassandra -p $operating_dir/pid/n${i}.pid
  i=`expr $i + 1`
done
