#!/bin/sh

os=`uname`
if [ ! $os = Linux ]; then
  echo Multi-machine remote run supports only Linux
  exit 1
fi

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig
. $scriptdir/ipman

my_ip=`ifconfig eth0 | grep "\<inet\>" | awk '{print $2}' | awk -F : '{print $2}'`
all_ip=`awk '{print $2}' $machinelist`

half=`expr $num_real_node / 2`
i=1
for ip in $all_ip; do
  if [ $ip = $my_ip ]; then
    cd $operating_dir
    ./allnode_start &
  else
    ssh $ip "cd $operating_dir; ./allnode_start" &
  fi
  i=`expr $i + 1`
  if [ $i -gt $half ]; then
    break
  fi
done
