#!/bin/sh

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig
. $scriptdir/ipman

cd $scriptdir

if ! [ -f $scriptdir/scdeploy.conf.exp ]; then
  echo There is no $scriptdir/scdeploy.conf.exp ...
  echo scdeploy.conf.exp is a scdeploy.conf without cassandra_data_dir assigned
  exit 1
fi

if [ -z "$test_size" ]; then
  test_size="16 "
fi

for n in $test_size; do
  echo Testing $n physical machines

  # configurations
  ./gen_nmc_machinelist $n
  cp scdeploy.conf.exp scdeploy.conf.$n
  echo "cassandra_log_dir=$cassandra_log_dir/n$n" >> scdeploy.conf.$n
  echo "cassandra_data_dir=$cassandra_data_dir/n$n" >> scdeploy.conf.$n

  cp scdeploy.conf.$n sdep0.conf
  cp scdeploy.conf.$n sdep1.conf

  div2=`expr ${n} / 2`
  split -l $div2 -d machinelist ml
  echo "machinelist=machinelist" >> scdeploy.conf.$n
  echo "machinelist=ml00" >> sdep0.conf
  echo "machinelist=ml01" >> sdep1.conf

  # experiments
  echo Setting operation dir...
  ./cluster_dir_setup scdeploy.conf.$n
  echo Running first half of the cluster...
  ./cluster_start sdep0.conf
  echo Ring gossip wait...
  sleep 90
  echo Load data...
  ../bin/cassandra-cli --host 192.168.1.1 -f /users/riza/sclck/data
  sleep 90
  echo Running second half of the cluster
  ./cluster_start sdep1.conf
  #../bin/nodetool --host 192.168.${n}.1 decommission
  echo Wait 5 minute for flapping count...
  sleep 300
  echo Stop entire cluster...
  ./cluster_stop scdeploy.conf.$n
  echo Collect logdir...
  ./cluster_collect_logdir scdeploy.conf.$n
  cd $cassandra_log_dir
  tarit n$n
  rm -r n$n
  cd $cwd
done

