#!/bin/sh

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig

my_ip=`ifconfig eth0 | grep "\<inet\>" | awk '{print $2}' | awk -F : '{print $2}'`
all_ip=`awk '{print $2}' $machinelist`

for ip in $all_ip; do
  if [ $ip = $my_ip ]; then
    cd $scriptdir
    sudo ./each_machine_ip_setup &
  else
    ssh -o "StrictHostKeyChecking no" $ip "cd $scriptdir; sudo ./each_machine_ip_setup" &
  fi
done
wait
