#!/bin/sh

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig

SSH_OPTION="StrictHostKeyChecking no"

my_ip=`ifconfig eth0 | grep "\<inet\>" | awk '{print $2}' | awk -F : '{print $2}'`
all_ip=`awk '{print $2}' $machinelist`

for ip in $all_ip; do
  if [ $ip = $my_ip ]; then
    cd $scriptdir
    ./each_machine_dir_setup $1 & 
  else
    now="`date`"
    ssh -o "$SSH_OPTION" $ip "sudo date --set='$now' > /dev/null; cd $scriptdir; ./each_machine_dir_setup $1" &
  fi
done
wait

