#!/bin/sh

os=`uname`
if [ ! $os = Linux ]; then
  echo Multi-machine IP setup script supports only Linux
  exit 1
fi

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig

mkdir $operating_dir || (echo "$operating_dir exists, cannot continue" ; exit 1)
sudo mount -t tmpfs -o size=2048M tmpfs $operating_dir

mkdir /tmp/cassandra
sudo mount -t tmpfs -o size=2048M tmpfs /tmp/cassandra

