#!/bin/sh

os=`uname`
if [ ! $os = Linux ]; then
  echo Multi-machine IP setup script supports only Linux
  exit 1
fi

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig

my_ip=`ifconfig eth0 | grep "\<inet\>" | awk '{print $2}' | awk -F : '{print $2}'`
my_id=`grep "\<$my_ip\>" $machinelist | awk '{print $1}'`

mkdir -p $operating_dir/lib
rm -r $operating_dir/lib/* 2> /dev/null
cp -r $cassandra_data_dir/machine$my_id/* $operating_dir/lib

