#!/bin/sh

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig

i=1
while [ $i -le $num_node ]; do
  cp -r $rawdata_dir $collecteddata_dir/machine1
  i=`expr $i + 1`
done

